ALTER TABLE params
ADD COLUMN duree_travail INTEGER NOT NULL DEFAULT 25,
ADD COLUMN duree_pause_courte INTEGER NOT NULL DEFAULT 5,
ADD COLUMN duree_pause_longue INTEGER NOT NULL DEFAULT 15,
ADD COLUMN objectif_sessions INTEGER NOT NULL DEFAULT 8;
